CREATE TABLE  ACCOUNT (
    ID VARCHAR2(20),
    PASSWORD VARCHAR2(20)
    );
    
    SELECT * FROM ACCOUNT;
    INSERT INTO ACCOUNT
    VALUES('KHUSER02','KHUSER02');
    GRANT RESOURCE TO KHUSER02;